name: Sync GitHub Pages
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js (use .nvmrc)
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
        env:
          PUBLIC_URL: /portfolio
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
        id: deployment
